### ISSUE TITLE
Feature Request: Extensions/Addons

### ISSUE THREAD

**Issue by anarchotaoist** [LeFroid/Viper-Browser#16]
Please add a suit of open source extensions that are commonly used;
eg Bitwarden, SimpleLogin, QOwnNotes, Plasma Integration, Play to Kodi.

Is there a tool that a non-tech person could use to port over Chrome extensions to QTwebengine?

Thanks.

**Comment by LeFroid** [comment]
Some extensions have, in a sense been implemented. There is a password storage and autofill system available to users with KWallet. Greasemonkey / Tampermonkey scripts are supported as well since the storage APIs have been ported.

A more comprehensive suite of extensions can be ported, if the required web APIs are implemented in the codebase. These APIs would have to be compatible with a QObject interface, so it can be passed through a QWebChannel instance to the client JavaScript code.

Some APIs would take trivial effort, others would take a manmouth effort, and I can certainly work to support anything within reason.

For any specific extensions, I would suggest looking at the permissions file or developer documentation pages to see which APIs are in use (would be the APIs described here, [https://developer.chrome.com/docs/extensions/reference/](https://developer.chrome.com/docs/extensions/reference/)), and then requesting those specific APIs to be implemented in the browser

**Comment by LeFroid** [comment]
Closing this issue- please refer to my above comment and feel free to raise another issue for any specific request.
